**Part A – Python & NumPy fundamentals (no dataset)**

**Question 1 :**  Write a Python program to check whether a number is even or odd using conditional statements.

In [1]:
def even_or_odd(n):
    if n % 2 == 0:
        return "Even"
    else:
        return "Odd"

for num in [4, 7, 0, -3, 10]:
    print(f"{num} is {even_or_odd(num)}")

4 is Even
7 is Odd
0 is Even
-3 is Odd
10 is Even

**Question 2 :** Write a Python program to count how many times a number appears in a list.
Example List
[2,3,4,2,5,2]

In [2]:
lst = [2, 3, 4, 2, 5, 2]
target = 2

# Manual loop
count = 0
for item in lst:
    if item == target:
        count += 1
print(f"Loop method    : {target} appears {count} times")

# Built-in
print(f"Built-in method: {target} appears {lst.count(target)} times")

Loop method    : 2 appears 3 times
Built-in method: 2 appears 3 times

**Question 3 :**  Generate an array from 1 to 20 with step size 2.

In [3]:
import numpy as np

arr3 = np.arange(1, 21, 2)
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19]

**Question 5 :** Convert a 1D array into 2x3 matrix:
arr = np.array([1,2,3,4,5,6]).

In [4]:
arr5 = np.array([1, 2, 3, 4, 5, 6])
matrix = arr5.reshape(2, 3)
print(matrix)
print("Shape:", matrix.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

**Question 9 :** Create a random array of 10 numbers and:
Find max and min
Sort the array

In [5]:
np.random.seed(42)
rand_arr = np.random.randint(1, 101, size=10)   # 10 integers between 1 and 100

print("Array  :", rand_arr)
print("Max    :", rand_arr.max())
print("Min    :", rand_arr.min())
print("Sorted :", np.sort(rand_arr))

Array  : [52 93 15 72 61 21 83 87 75 75]
Max    : 93
Min    : 15
Sorted : [15 21 52 61 72 75 75 83 87 93]

**Question 10 :** Replace all even numbers with 0:
arr = np.array([1,2,3,4,5,6])

In [6]:
arr10 = np.array([1, 2, 3, 4, 5, 6])
mask = arr10 % 2 == 0          # [False, True, False, True, False, True]
arr10[mask] = 0
print(arr10)

[1 0 3 0 5 0]

**Part B – Pandas on the Retail Dataset**

In [11]:
import pandas as pd

df = pd.read_csv("retail_dataset(1).csv")
print("Shape:", df.shape)
print()
df.info()
print()
print("Missing values per column:")
print(df.isna().sum())

Shape: (100, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

Missing values per column:
Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

**Question 4 :** Create a new column called Revenue, where:
Revenue = Quantity × Price
Display the updated dataset with the new column.

In [12]:
df["Revenue"] = df["Quantity"] * df["Price"]

print("Rows where Revenue could not be computed (missing Quantity or Price):",
      df["Revenue"].isna().sum())
df

Rows where Revenue could not be computed (missing Quantity or Price): 7

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
...,...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North,29010.0
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North,9693.0
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North,4501.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North,9464.0

**Question 6 :** Slicing Data
1) Select first 10 rows
2) Select only "Product Category" and "Quantity" columns

In [13]:
df.head(10)

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
5,T006,C042,Electronics,10.0,866.0,28-12-2024,West,8660.0
6,T007,C022,Furniture,3.0,2340.0,09-04-2023,East,7020.0
7,T008,C023,Clothing,7.0,881.0,14-11-2024,West,6167.0
8,T009,C008,Electronics,8.0,780.0,26-12-2024,East,6240.0
9,T010,C003,Furniture,5.0,1617.0,30-06-2024,North,8085.0

In [14]:
df[["Product Category", "Quantity"]]

   Product Category  Quantity
0             Books       7.0
1              Toys       4.0
2         Furniture       8.0
3         Groceries       5.0
4             Books       7.0
..              ...       ...
95        Furniture      10.0
96         Clothing       9.0
97         Clothing       7.0
98        Groceries       9.0
99        Furniture       8.0

[100 rows x 2 columns]

**Question 7 :** Find all records where:

Region = "South" and Quantity > 2

In [15]:
south_filtered = df[(df["Region"] == "South") & (df["Quantity"] > 2)]
print("Matching records:", len(south_filtered))
south_filtered

Matching records: 17

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
24,T025,C022,Electronics,9.0,751.0,29-08-2023,South,6759.0
32,T033,C022,Furniture,5.0,2707.0,24-06-2024,South,13535.0
39,T040,C004,Toys,4.0,778.0,31-07-2024,South,3112.0
40,T041,C041,Toys,9.0,NaN,12-11-2024,South,NaN
44,T045,C049,Clothing,10.0,934.0,28-01-2023,South,9340.0
55,T056,C010,Books,4.0,434.0,13-08-2023,South,1736.0
60,T061,C049,Sports,4.0,990.0,19-09-2024,South,3960.0
61,T062,C028,Clothing,6.0,1323.0,16-09-2023,South,7938.0
69,T070,C041,Electronics,9.0,711.0,13-08-2023,South,6399.0
70,T071,C020,Sports,8.0,408.0,22-08-2023,South,3264.0
76,T077,C025,Furniture,9.0,995.0,16-04-2024,South,8955.0
79,T080,C015,Toys,9.0,1061.0,23-04-2023,South,9549.0
90,T091,C011,Electronics,3.0,980.0,22-03-2023,South,2940.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0

**Question 8 :** Display:
1) The first 10 rows of the dataset.
2) Rows 15 to 25.

In [16]:
df.iloc[:10]

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
5,T006,C042,Electronics,10.0,866.0,28-12-2024,West,8660.0
6,T007,C022,Furniture,3.0,2340.0,09-04-2023,East,7020.0
7,T008,C023,Clothing,7.0,881.0,14-11-2024,West,6167.0
8,T009,C008,Electronics,8.0,780.0,26-12-2024,East,6240.0
9,T010,C003,Furniture,5.0,1617.0,30-06-2024,North,8085.0

In [17]:
df.iloc[14:25]

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
14,T015,C010,Sports,6.0,803.0,06-08-2023,East,4818.0
15,T016,C029,Clothing,5.0,639.0,17-05-2024,North,3195.0
16,T017,C004,Toys,2.0,423.0,02-02-2024,South,846.0
17,T018,C039,Toys,8.0,NaN,28-01-2024,NaN,NaN
18,T019,C022,Sports,6.0,1328.0,26-07-2023,East,7968.0
19,T020,C045,Toys,2.0,962.0,15-01-2023,South,1924.0
20,T021,C043,Books,NaN,516.0,07-07-2024,East,NaN
21,T022,C042,Electronics,1.0,1971.0,05-04-2024,East,1971.0
22,T023,C015,Beauty,10.0,174.0,21-11-2024,North,1740.0
23,T024,C012,Clothing,6.0,236.0,28-07-2024,West,1416.0
24,T025,C022,Electronics,9.0,751.0,29-08-2023,South,6759.0